import random
print("#######################")
print("# jogo de adivinhação #")
print("#  Welliton h.        #")
print("#                     #")
print("#  #    #     #       #")
print("#  #   # #    #       #")
print("#   # #   #  #        #")
print("#    #     #          #")
print("#                     #")
print("#  #       #          #")
print("#  #       #          #")
print("#  # # # # #          #")
print("#  #       #          #")
print("#  #       #          #")
print("#                     #")
print("#  #                  #")
print("#  #     ###########  #")
print("#  #                  #")
print("#  #                  #")
print("#        ###########  #")
print("#  #                  #")
print("#                     #")
print("#######################")
numeroSecreto = random.randrange(0,100)
totaltentativas = 0
pontos = 100
